name: myposh
description: my posh
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animated_snack_bar: ^0.3.1
  bloc: ^8.1.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  image_picker: ^1.0.4
  lottie: ^2.6.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.0
  cached_memory_image: ^1.3.1
  show_network_image: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/photo_border.png
